// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import {env} from "./src/config/env.js";
import { defineConfig } from "prisma/config";



const databaseUrl = env.DATABASE_URL;

if (!databaseUrl) {
  throw new Error("DATABASE_URL is not set. Add it to your .env file.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
